FROM ubuntu:18.04

MAINTAINER DonghoonHan <dhk1349@gmail.com>
LABEL "purpose"="demo"

EXPOSE 8000
RUN apt-get update 
RUN apt-get install git -y 
RUN apt-get install python3-pip -y
RUN pip3 install --upgrade pip

ARG CACHEBUST=1
RUN echo "$CACHEBUST"
RUN git clone "https://github.com/itsnamgyu/ml-service-demo" 
WORKDIR ./ml-service-demo
RUN pip3 install --no-cache-dir  -r requirements.txt


